// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Config {
    /**
     * Creates a new Config instance.
     * @param {Partial<Config>} [$$source = {}] - The source object to create the Config.
     */
    constructor($$source = {}) {
        if (!("whisperModel" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["whisperModel"] = "";
        }
        if (!("useOllama" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["useOllama"] = false;
        }
        if (!("ollamaModel" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ollamaModel"] = "";
        }
        if (!("hotkey" in $$source)) {
            /**
             * @member
             * @type {HotkeyConfig}
             */
            this["hotkey"] = (new HotkeyConfig());
        }
        if (!("llmPrompt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["llmPrompt"] = "";
        }
        if (!("filterHallucinations" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["filterHallucinations"] = false;
        }
        if (!("pauseMediaOnRecord" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["pauseMediaOnRecord"] = false;
        }
        if (!("microphone" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["microphone"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Config}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("hotkey" in $$parsedSource) {
            $$parsedSource["hotkey"] = $$createField3_0($$parsedSource["hotkey"]);
        }
        return new Config(/** @type {Partial<Config>} */($$parsedSource));
    }
}

export class HotkeyConfig {
    /**
     * Creates a new HotkeyConfig instance.
     * @param {Partial<HotkeyConfig>} [$$source = {}] - The source object to create the HotkeyConfig.
     */
    constructor($$source = {}) {
        if (!("modifiers" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["modifiers"] = [];
        }
        if (!("keys" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["keys"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HotkeyConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HotkeyConfig}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("modifiers" in $$parsedSource) {
            $$parsedSource["modifiers"] = $$createField0_0($$parsedSource["modifiers"]);
        }
        if ("keys" in $$parsedSource) {
            $$parsedSource["keys"] = $$createField1_0($$parsedSource["keys"]);
        }
        return new HotkeyConfig(/** @type {Partial<HotkeyConfig>} */($$parsedSource));
    }
}

export class TranscriptionEntry {
    /**
     * Creates a new TranscriptionEntry instance.
     * @param {Partial<TranscriptionEntry>} [$$source = {}] - The source object to create the TranscriptionEntry.
     */
    constructor($$source = {}) {
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["timestamp"] = 0;
        }
        if (!("whisperTime" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["whisperTime"] = 0;
        }
        if (!("whisperOutput" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["whisperOutput"] = "";
        }
        if (!("llmTime" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["llmTime"] = 0;
        }
        if (!("llmOutput" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["llmOutput"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TranscriptionEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TranscriptionEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TranscriptionEntry(/** @type {Partial<TranscriptionEntry>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = HotkeyConfig.createFrom;
const $$createType1 = $Create.Array($Create.Any);
