// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * JTTService exposes methods to the frontend
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "./internal/config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as recorder$0 from "./internal/recorder/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<$models.DependencyStatus>}
 */
export function CheckDependencies() {
    return $Call.ByID(2562512724).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} name
 * @param {string} url
 * @returns {$CancellablePromise<void>}
 */
export function DownloadWhisperModel(name, url) {
    return $Call.ByID(1739716008, name, url);
}

/**
 * @returns {$CancellablePromise<$models.WhisperModel[]>}
 */
export function GetAvailableWhisperModels() {
    return $Call.ByID(728014776).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<config$0.Config | null>}
 */
export function GetConfig() {
    return $Call.ByID(724951059).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetDefaultPrompt() {
    return $Call.ByID(1623546800);
}

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function GetDownloadedModels() {
    return $Call.ByID(1274740742).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @returns {$CancellablePromise<config$0.TranscriptionEntry[]>}
 */
export function GetHistory() {
    return $Call.ByID(2594147347).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetLogPath() {
    return $Call.ByID(1638957486);
}

/**
 * @returns {$CancellablePromise<recorder$0.Microphone[]>}
 */
export function GetMicrophones() {
    return $Call.ByID(3309817626).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function GetOllamaModels() {
    return $Call.ByID(3782478637).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetRecentLogs() {
    return $Call.ByID(1711462601);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetState() {
    return $Call.ByID(263894850);
}

/**
 * @param {string} dep
 * @returns {$CancellablePromise<void>}
 */
export function InstallDependency(dep) {
    return $Call.ByID(1145005019, dep);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function IsOllamaRunning() {
    return $Call.ByID(2205589612);
}

/**
 * @param {config$0.Config | null} cfg
 * @returns {$CancellablePromise<void>}
 */
export function SaveConfig(cfg) {
    return $Call.ByID(2215473916, cfg);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function StartRecording() {
    return $Call.ByID(3684954612);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function StopRecording() {
    return $Call.ByID(3172466554);
}

/**
 * @param {string[]} modifiers
 * @param {string} key
 * @returns {$CancellablePromise<void>}
 */
export function UpdateHotkey(modifiers, key) {
    return $Call.ByID(1119532648, modifiers, key);
}

// Private type creation functions
const $$createType0 = $models.DependencyStatus.createFrom;
const $$createType1 = $models.WhisperModel.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = config$0.Config.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $Create.Array($Create.Any);
const $$createType6 = config$0.TranscriptionEntry.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = recorder$0.Microphone.createFrom;
const $$createType9 = $Create.Array($$createType8);
