// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class DependencyStatus {
    /**
     * Creates a new DependencyStatus instance.
     * @param {Partial<DependencyStatus>} [$$source = {}] - The source object to create the DependencyStatus.
     */
    constructor($$source = {}) {
        if (!("sox" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["sox"] = false;
        }
        if (!("whisper" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["whisper"] = false;
        }
        if (!("ollama" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ollama"] = false;
        }
        if (!("hasModel" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasModel"] = false;
        }
        if (!("nowPlaying" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["nowPlaying"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DependencyStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DependencyStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DependencyStatus(/** @type {Partial<DependencyStatus>} */($$parsedSource));
    }
}

export class WhisperModel {
    /**
     * Creates a new WhisperModel instance.
     * @param {Partial<WhisperModel>} [$$source = {}] - The source object to create the WhisperModel.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["size"] = "";
        }
        if (!("speed" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["speed"] = "";
        }
        if (!("quality" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["quality"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WhisperModel instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WhisperModel}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WhisperModel(/** @type {Partial<WhisperModel>} */($$parsedSource));
    }
}
